### ISSUE TITLE
安装成功，可以订阅RSS,但“设置”里面的“插件”空白，没法启用Mercury_fulltext、Fever等插件

### ISSUE THREAD

**Issue by pundits** [HenryQW/docker-ttrss-plugins#15]
在linode上，centos 7 X64位，通过 docker-compose 部署成功，可以订阅RSS,但“设置”里面的“Plugins”项空白，没法启用Mercury_fulltext、Fever等插件。另外，点击“设置”里面的“feeds”选项，会进入死循环，不能正常退出，只能关闭浏览器。

**Comment by HenryQW** [comment]
浏览器 console 是否有错误？

**Comment by pundits** [comment]
我是菜鸟，没看懂你这话的意思？但浏览器chrome, ie , Firefox  都不能看到插件。Firefox  不会死循环。

**Comment by HenryQW** [comment]
chrome 访问 ttrss，按 F12，然后进行操作。

![image](https://user-images.githubusercontent.com/5896343/54210767-06d8b180-44d8-11e9-9555-abb45d1e146e.png)

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/54210857-2cfe5180-44d8-11e9-9cea-805c3c5d285d.png)

这是我的 ttrss，最新版没有任何问题，不管任何OS，docker 都应该是一样的。

推荐试一试 docker pull wangqiru/ttrss:latest，然后重新部署。

**Comment by pundits** [comment]
![1](https://user-images.githubusercontent.com/20499386/54258691-600b1880-459e-11e9-9003-f37886ee2008.PNG)

**Comment by HenryQW** [comment]
什么报错都没有，我又重新部署了一次，无法复现你说的问题。

**Comment by pundits** [comment]
按你所说的， docker pull wangqiru/ttrss:latest 重新部署，正常了。什么原因？

**Comment by HenryQW** [comment]
无法复现不知道原因。

插件设置页需要填写 `service.mercury:3000`。

**Comment by DHPO** [comment]
> 无法复现不知道原因。
> 
> 插件设置页需要填写 `service.mercury:3000`。

建议在文档中明确一下

**Comment by HenryQW** [comment]
@DHPO 有空的吧，这太基础了容易被我忽略掉。

**Comment by next-9527** [comment]
请问一下docker部署了tts之后怎么才能添加新的插件，我已经在plugins目录里git了插件，但是在tts的插件里根本找不到我git的新插件

**Comment by HenryQW** [comment]
> 请问一下docker部署了tts之后怎么才能添加新的插件，我已经在plugins目录里git了插件，但是在tts的插件里根本找不到我git的新插件

见https://github.com/HenryQW/Awesome-TTRSS/issues/194#issuecomment-705613156

目录中themes改为plugins

**Comment by next-9527** [comment]
> > 请问一下 docker 部署了 tts 之后如何才能添加新的插件，我已经在插件目录里 git 了插件，但是在 tts 的插件里根本找到我 git 的新插件
> 
> 见[＃194（评论）](https://github.com/HenryQW/Awesome-TTRSS/issues/194#issuecomment-705613156)
> 
> 目录中主题转换插件

我尝试了您说的方法，修改了docker-compose.yml，已经把容器plugins映射到主机，在主机plugins文件夹git插件成功之后，在容器里看不到新添加的插件，同时tinytinyrss插件选项里也没有出现新的插件,没有任何效果。
之前我尝试过直接通过docker exec -it containerID /bin/sh进入到tinytinyrss的容器内，然后在容器内的plugins.local文件夹内直接git插件，这样可以看到新添加的插件，但是在tinytinyrss插件设置里仍然看不到新添加的插件（还是原来那些插件，没有任何变化，重启容器也没有变化）

**Comment by next-9527** [comment]
> > 请问一下 docker 部署了 tts 之后怎么才能添加新的插件，我已经在 plugins 目录里 git 了插件，但是在 tts 的插件里根本找不到我 git 的新插件
> 
> 见[#194 (comment)](https://github.com/HenryQW/Awesome-TTRSS/issues/194#issuecomment-705613156)
> 
> 目录中 themes 改为 plugins

抱歉，我搞懂了，原来是要改为plugins而不是plugins.local。#尴尬
可以问一下您怎么才能把docker里的插件导出到外部的plugins文件夹吗？
