### ISSUE TITLE
无法从指定的网址下载:; 28 Connection timed out after 15000 milliseconds

### ISSUE THREAD

**Issue by Zxilly** [HenryQW/docker-ttrss-plugins#16]
* ## _What_ is the issue?
无法从指定的网址下载:; 28 Connection timed out after 15000 milliseconds

* ## _What_ is your OS and its version?
CentOS 7 Latest

* ## _What_ is your installation method?

* ### Docker

 测试了 Docker 内 ping 没有问题
链接是 https://rsshub.app/bilibili/user/video/9838560.rss
在宿主机上使用 curl 可以正常获取

**Comment by HenryQW** [comment]
和这个 repo 没有关系。

RSSHub demo 不保证稳定性，推荐自建。

我自己订阅了十几个自建 RSSHub 源，没有这个问题。

**Comment by songquanxu** [comment]
我在自建源中遇到了同样的问题，rsshub+ttrss，docker部署的。

**Comment by lovewhowho17** [comment]
同样，不管用自己服务器还是RSSHUB都一样

**Comment by SunsetjesusCame2me** [comment]
同，自建的rsshub-server，楼上有解决这个问题吗？

**Comment by jackwillwu** [comment]
Docker自建Tinytinyrss + rsshub
系统：Ubuntu-22.04云服务器
解决思路：进入tinytinyrss docker容器内部，修改/var/www/classes文件夹下config.php，TIMEOUT数字改成120
解决方法：先找到容器id
docker ps <container_id>
docker exec -it <container_id>  /bin/sh
cd classes
vi config.php

修改以下四行
                Config::FEED_FETCH_TIMEOUT => [ 120,                                                            Config::T_INT ],
                Config::FEED_FETCH_NO_CACHE_TIMEOUT => [ 120,                                   Config::T_INT ],
                Config::FILE_FETCH_TIMEOUT => [ 120,                                                            Config::T_INT ],
                Config::FILE_FETCH_CONNECT_TIMEOUT => [ 120,   

数字全改成120
最后 ufw allow 443 打开端口
我是这样解决的

**Comment by vector090** [comment]
> Docker自建Tinytinyrss + rsshub 系统：Ubuntu-22.04云服务器 解决思路：进入tinytinyrss docker容器内部，修改/var/www/classes文件夹下config.php，TIMEOUT数字改成120 解决方法：先找到容器id docker ps <container_id> docker exec -it <container_id> /bin/sh cd classes vi config.php
> 
> 修改以下四行 Config::FEED_FETCH_TIMEOUT => [ 120, Config::T_INT ], Config::FEED_FETCH_NO_CACHE_TIMEOUT => [ 120, Config::T_INT ], Config::FILE_FETCH_TIMEOUT => [ 120, Config::T_INT ], Config::FILE_FETCH_CONNECT_TIMEOUT => [ 120,
> 
> 数字全改成120 最后 ufw allow 443 打开端口 我是这样解决的 [参考](https://community.tt-rss.org/t/28-operation-timed-out-after-15000-milliseconds-with-0-bytes-received-it-can-be-more/2118)

如果是 docker 方式起的 tt-rss, 推荐用环境变量 .env 的方式来配置
TTRSS_FEED_FETCH_TIMEOUT=120                                                                                                                                                                                                                                  
TTRSS_FEED_FETCH_NO_CACHE_TIMEOUT=120                                                                                                                                                                                                                         
TTRSS_FILE_FETCH_CONNECT_TIMEOUT=120                                                                                                                                                                                                                          
TTRSS_FILE_FETCH_TIMEOUT=120   

参考 https://tt-rss.org/wiki/GlobalConfig/
