### ISSUE TITLE
mercury_fulltext does not work

### ISSUE THREAD

**Issue by wgqimut** [HenryQW/docker-ttrss-plugins#18]
* ## _What_ is the issue?
使用docker-compose部署之后, 也设置了mercury_fulltext的API(严格按照步骤), 但是好像并没有用, The verge的还是有"Continue reading", 并没有把全文直接抓下来. 博客园的好像也是这样的. 

然后我用mercury_fulltext的docker单独部署了一次, 用一个网页测试, 发现确实解析不了, 报错了
```
[root@centos ~]# curl localhost:3000/parse?url=https://www.theverge.com/2019/3/16/18267023/aladdin-avengers-endgame-booksmart-new-trailers
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /parse</pre>
</body>
</html>
```
mercury_fulltext image版本: 2b8ec2bb269a (最新的版本应该是)

**Comment by HenryQW** [comment]
Get /parser
