### ISSUE TITLE
关于一个订阅源格式的问题

### ISSUE THREAD

**Issue by Derekmini** [HenryQW/docker-ttrss-plugins#24]
* ## _What_ is the issue?

我这里有一个杂志目录的订阅源，这个订阅源好像是更改了RSS的格式，在浏览器中可以直接打开，但ttRSS获取时提示如下错误：

`[10:43:04/38] start`
`[10:43:04/38] local cache will not be used for this feed`
`[10:43:04/38] last unconditional update request: 2019-04-22 10:42:57`
`[10:43:04/38] stored last modified for conditional request: Sat, 20 Apr 2019 07:01:14 GMT`
`[10:43:04/38] fetching [https://asa.scitation.org/action/showFeed?type=etoc&feed=rss&jc=jas] (force_refetch: 1)...`
`[10:43:04/38] fetch done.`
`[10:43:04/38] source last modified: Sat, 20 Apr 2019 07:01:14 GMT`
`[10:43:04/38] saving cache/feeds/748d1876a7e4d2ada91c75410de605a7293dbc12.xml`
`[10:43:04/38] fetch error: Unknown/unsupported feed type`

* ## _What_ is your OS and its version?

Debian 9

* ## _What_ is your installation method?

### Docker

  * Did you build your own dockerfile (paste it here if possible)?
I use 
`git clone https://github.com/HenryQW/docker-ttrss-plugins && cd docker-ttrss-plugins
`
`nano docker-compose.yml`后修改主机IP地址
`cd docker-ttrss-plugins && docker-compose up -d`开始抓取并安装

  * _What_ is your setup? (PHP version, database used, etc.)
    

* ## _Are_ there any error logs?

`[10:43:04/38] start`
`[10:43:04/38] local cache will not be used for this feed`
`[10:43:04/38] last unconditional update request: 2019-04-22 10:42:57`
`[10:43:04/38] stored last modified for conditional request: Sat, 20 Apr 2019 07:01:14 GMT`
`[10:43:04/38] fetching [https://asa.scitation.org/action/showFeed?type=etoc&feed=rss&jc=jas] (force_refetch: 1)...`
`[10:43:04/38] fetch done.`
`[10:43:04/38] source last modified: Sat, 20 Apr 2019 07:01:14 GMT`
`[10:43:04/38] saving cache/feeds/748d1876a7e4d2ada91c75410de605a7293dbc12.xml`

* ## _How_ can the issue be replicated?

在ttRSS中订阅这个源，在源上右键`Debug feed`，勾选`Force refetch`，`continue`后得到如上报错结果。

* ## Other Comments

I solemnly swear that **I have googled for solutions and the issue is unprecedented**.
我的确Google了，Google关键词`type=etoc`，的确没有找到相关的类型如何更改。另外，我考虑到可能是ttRSS缺少插件，所以在`inoreader`上也试了一下，可以正常提取，但提取到的内容都是一个月之前的，近期的内容没有更新，可能是从那个时候开始换了格式；
另外再电脑上，使用订阅软件也无法正确识别这个源，提示`Feed的url不存在`。

请问，如何才能获取到该源中的内容？是更改这个源的格式吗？还是可以通过插件进行转换？谢谢！

**Comment by HenryQW** [comment]
看了一下这个源地址生成的 XML 不符合 RSS 标准，是其他的奇奇怪怪的 RSS 标准（可能是 RDF，学术源好像都喜欢 RDF）。TTRSS 不支持这个标准，可以尝试用其他支持该标准的阅读器，Mac/iOS 端推荐 Reeder。

**Comment by Derekmini** [comment]
谢谢！我大致清楚了！
