### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by majie1993** [HenryQW/docker-ttrss-plugins#25]
1. Reeder 4 now has a good compatibility with fever, so the caution in the README should be removed.
2. [Suggest] Is there any possible to add [Sphinx](https://git.tt-rss.org/fox/tt-rss/wiki/SphinxSearch) dependency directly into the Dockerfile?

**Comment by HenryQW** [comment]
1. No it doesn’t work.
1. AFAIK, Sphinx plugin is in maintenance mode, plus unlike other plugins, enabling it also requires modification to the config.php, which introduces extra complexity. PR is welcome but please **make it optional.**

**Comment by majie1993** [comment]
You're right. Finally, this issue fixed in today's update.

**Comment by HenryQW** [comment]
Was actually fixed by a updated fever plugin. dca68442ae60ddce1132bd8ce64f4d9729828071

Happy rssing.
