### ISSUE TITLE
能否添加tt-rss-newsplus-plugin插件

### ISSUE THREAD

**Issue by bebound** [HenryQW/docker-ttrss-plugins#26]
https://github.com/voidstern/tt-rss-newsplus-plugin

可以加快fiery feeds的ttrss文章同步速度。ttrss默认一个请求只能传输200个文章id， 7w个未读文章有点同步不来。

另外请教下，如果只想同步部分文件夹夹的话，目前只能手动创建一个新账号用来给rss阅读器使用吗？ttrss不支持opml导入，每次添加订阅源在这个新账户中再添加一次，有点麻烦。目前好像也没有阅读器支持部分文件夹同步。

谢谢。

ps 今天试用了下fiery rss，感觉蛮好用的，而且是freemium模式。

**Comment by HenryQW** [comment]
欢迎 PR，近期注意力不在这个项目上。
7w 未读？可以考虑下先退订一部分。
