### ISSUE TITLE
你好，用 Docker Compose ，创建失败。

### ISSUE THREAD

**Issue by laotong** [HenryQW/docker-ttrss-plugins#5]
你好，用 Docker Compose ，创建失败。

错误 | 2018/06/11 22:25:43 | Container | admin | Failed to do background task (application_custom, ttrss)
-- | -- | -- | -- | --
错误 | 2018/06/11 22:25:43 | Container | admin | Background task error for application_custom ttrss: Error: Not Found ("pull access denied for ttest, repository does not exist or may require 'docker login'")
信息 | 2018/06/11 22:25:39 | Container | admin | Start to do background task (application_custom, ttrss)

这个ttest这个现在没有了吗

**Comment by HenryQW** [comment]
已修复 https://github.com/HenryQW/docker-ttrss-plugins/commit/1bb244f9a90bf4ae14b125d7235e37d5747515d4

**Comment by laotong** [comment]
修复后的第八行，端口号错了

**Comment by HenryQW** [comment]
容器pg默认对外暴露5433端口，防止和宿主已有pg冲突。ttrss通过docker内网能够直接解析到容器pg。
