### ISSUE TITLE
使用 Reeder iOS 提示密码错误无法登录

### ISSUE THREAD

**Issue by dongleizhang** [HenryQW/docker-ttrss-plugins#6]
* ## _What_ is the issue?

开启了 Fever 插件，但是使用 Reeder iOS 提示密码错误无法登录。使用了 admin 作为 email，并使用了插件页面里设置的密码。

* ## _What_ is your OS and its version?

Ubuntu 16.4 + iOS 11.4 Reeder 3

* ## _What_ is your installation method?

* ### Docker

  * Did you build your own dockerfile (paste it here if possible)?

只是使用了 `docker-compose up -d`. 并按照说明修改了 `.yml` 中的三处位置，域名是 http，没有没有开启 ssl 证书。（事实上，采用 CloudFlare 的 HTTPS 模式也是无法登录，似乎是无法保存密码）

* ### Old-fashion way

  * _What_ is your setup? (PHP version, database used, etc.)
    

* ### Others

* ## _Are_ there any error logs?
No error logs.

* ## _How_ can the issue be replicated?

* ## Other Comments

I solemnly swear that **I have googled for solutions and the issue is unprecedented**.

**Comment by cocakuma** [comment]
感谢，开启 api 权限就好了
